### PR TITLE
Added support for sub-directories within source folder

### PR DESCRIPTION
**Pull request by robertmesserle**
As my project has grown, not being able to use directory structures to organize my files was very limiting.  I made a small tweak to add support for a directory structure.

### CODE REVIEW

**Comment by robertmesserle** [comment]
Nevermind, found a bug in the output, going to try to fix it and re-open.

**Comment by arobson** [comment]
Hi Robert,

Fixing this would be awesome. You're not the only one who's mentioned that this is a major limiting factor. Sorry I haven't had a chance to get to it lately, but I think it's great that you've spent some time working on a fix. Looking forward to seeing the next pull request.

Thanks!
Alex

**Comment by arobson** [comment]
Hi Robert,

Thanks for your work on this. Unfortunately, this approach breaks some behavior (and unit tests). Looking over how you were solving this gave me some ideas and I was able to put something together that passes the tests and supports relative import statements (so you can use ../ to refer up the hierarchy as well).

Thanks again,
Alex

**Comment by robertmesserle** [comment]
Ah, great!  I figured you'd likely be able to come up with something a bit better than my (admittedly hacky) solution, given greater familiarity with the code.  Glad I could (kinda) help!

**Pull request closed without merging**
